name: Build

on: 
  pull_request:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bajja.txt"
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          draft: true
          tag: "pre-v.1.0.0"

      - name: Create file
        run: |
          echo > bajja.txt

