name: Build

on: 
  pull_request:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create file
        run: |
          echo > bajja.txt

      - name: Create file2
        run: |
          echo > bajja2.txt

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bajja.txt, bajja2.txt"
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          draft: true
          tag: "pre-v.1.0.0"


